# Generated by Django 4.2.1 on 2023-06-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_topic_space_host_message_space_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
